name: qiandao

on:
  push:
    branches: [main]
  schedule:
    - cron: 20 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: my-org/my-tools

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Install pipfile
        run: |
          pipenv install
      - name: pipenv shell
        run: |
          pipenv run python run.py nexusphp signin
        env:
          CONFIG: ${{ secrets.PT_TOOLS_CONFIG }}
